from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time
service=Service(executable_path="C:\\Users\\dell\\Downloads\\chromedriver_win32\\chromedriver.exe")
driver=webdriver.Chrome()
driver.get("https://oro-staging.lawsonproducts.com/")
register=driver.find_element(By.LINK_TEXT,"Log In or Register").click()
customer=driver.find_element(By.XPATH,'//span[contains(text(),"I am a new customer.")]').click()
next=driver.find_element(By.XPATH,'//input[@value="Next"]').click()
wait=WebDriverWait(driver,10)
firstname=wait.until(EC.presence_of_element_located((By.NAME,"oro_customer_frontend_customer_user_register[firstName]"))).send_keys("Rajasree")
lastname=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[lastName]").send_keys("Gorrepati")
email=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[email][first]").send_keys("renukadagini449@gmail.com")
confirm_mail=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[email][second]").send_keys("renukadagini449@gmail.com")
user_id=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[login]")
password=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[plainPassword][first]").send_keys("31@Raji")
confirm=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[plainPassword][second]").send_keys("31@Raji")
question=Select(driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[security_question]"))
question.select_by_value('CITY')
answer=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[answer]").send_keys("ongole")
comapny=driver.find_element(By.NAME,'oro_customer_frontend_customer_user_register[addresses][company_name]').send_keys("abc")
role=Select(driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[title]"))
role.select_by_value("Other")
other=driver.find_element(By.NAME,'oro_customer_frontend_customer_user_register[title_text]').send_keys("student")
#add1=driver.find_element(By.NAME,'oro_customer_frontend_customer_user_register[addresses][street]').send_keys("ongole,AP")
add2=driver.find_element(By.NAME,'oro_customer_frontend_customer_user_register[addresses][street2]').send_keys("vennuru,AP")
city=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][city]").send_keys("ongole")
country=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][county]").send_keys("India")
region=Select(driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][region]"))
region.select_by_value("US-NJ")
zipcode=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][postalCode]").send_keys("07001")
cont=Select(driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][country]"))
cont.select_by_value("US")
phone=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][phone]").click()
driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][phone]").send_keys("(222)222-2222")
ext=driver.find_element(By.NAME,"oro_customer_frontend_customer_user_register[addresses][phone_ext]").send_keys("709")
acc=driver.find_element(By.XPATH,'//strong[contains(text(),"Account will be used for government purposes.")]').click()
account=driver.find_element(By.XPATH,'//strong[contains(text(),"Account is tax exempt.")]').click()
agree=driver.find_element(By.LINK_TEXT,"Terms and Conditions").click()
text="These Terms and Conditions of Sale will be governed under the laws of the State of Illinois without regard to its conflicts of law provisions."
w=WebDriverWait(driver,10)
element =wait.until(EC.visibility_of_element_located((By.XPATH, f"//*[contains(text(), '{text}')]")))
driver.execute_script("arguments[0].scrollIntoView();", element)
next=driver.find_element(By.XPATH,'//button[contains(text(),"Agree")]').click()
submit=driver.find_element(By.NAME,'create').click()
time.sleep(10)
driver.close()